### ISSUE TITLE
If user's locale is not installed in proxmox, ssh calls all fail.

### ISSUE THREAD

**Issue by juledwar** [swayf/proxmoxer#28] opened 2017-03-08 01:27 UTC
When using Proxmoxer via the ssh method, if your local is not available on the Proxmox host then there's some warnings in the stderr that's returned to the call site, which results in the code thinking that it's a fatal error and returns a 500 status in the response.

```
ipdb> full_cmd
'pvesh get /nodes/proxmox15/qemu'
ipdb> n
> proxmoxer/backends/base_ssh.py(46)request()
     45         stdout, stderr = self._exec(full_cmd)
---> 46         try:
     47             status_code = int(stderr.split()[0])

ipdb> stderr
'perl: warning: Setting locale failed.\nperl: warning: Please check that your locale settings:\n\tLANGUAGE = (unset),\n\tLC_ALL = (unset),\n\tLC_TIME = "en_GB.UTF-8",\n\tLANG = "en_US.UTF-8"\n    are supported and installed on your system.\nperl: warning: Falling back to a fallback locale ("en_US.UTF-8").\n200 OK'
```

which ends up causing:

```
ValueError: "invalid literal for int() with base 10: 'perl:'"
> proxmoxer/backends/base_ssh.py(47)request()
     46         try:
---> 47             status_code = int(stderr.split()[0])
     48         except:
```

**Comment by juledwar** [comment] 2017-03-08 01:27
I can work around this by setting LC_ALL=C, but it's still wasted 2 hours of my day working out what's going on, so a fix would be warranted and welcome!

**Comment by swayf** [comment] 2017-12-02 15:12
hm.. looks for me as not a bug of proxmoxer..

**Comment by juledwar** [comment] 2017-12-04 00:59
It is _absolutely_ a proxmoxer error @swayf 

It's assuming ANYTHING on stderr is an HTTP error string starting with a number, when in this case it is not an error it's just a warning from the remote shell and the proxmoxer code is trying to parse it.

**Comment by juledwar** [comment] 2017-12-04 01:02
Notice that there's a newline '\n' follwed by
"200 OK"
which is the part it's trying to parse.

A trivial fix would be to only parse the last line of the output.

**Comment by bigjools** [comment] 2017-12-04 10:01
Looks like this was already fixed in https://github.com/swayf/proxmoxer/pull/30 anyway.

**Comment by swayf** [comment] 2017-12-04 21:07
ok ... now I see =)) I misunderstood your first description

**Closed by swayf** 2017-12-04 21:07 UTC
